# Generated by Django 3.0.8 on 2021-01-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='User Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(verbose_name="Reservation's description"),
        ),
    ]
